-- 코드를 입력하세요
# SELECT DATE_FORMAT(SALES_DATE, "%Y") AS YEAR, DATE_FORMAT(SALES_DATE, "%c") AS MONTH, GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
# FROM USER_INFO AS U INNER JOIN ONLINE_SALE AS O ON U.USER_ID = O.USER_ID
# WHERE GENDER IS NOT NULL
# GROUP BY YEAR, MONTH, GENDER
# ORDER BY YEAR, MONTH, GENDER

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO AS U INNER JOIN ONLINE_SALE AS O ON U.USER_ID = O.USER_ID
GROUP BY YEAR, MONTH, GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER