-- 코드를 입력하세요
# SELECT H.CAR_ID, P.CAR_TYPE, DAILY_FEE AS FEE
# FROM CAR_RENTAL_COMPANY_CAR AS C INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE = P.CAR_TYPE
# WHERE (P.CAR_TYPE LIKE "세단" OR "SUV") AND START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-30' AND DAILY_FEE * 30 * DISCOUNT_RATE >= 500000 AND DAILY_FEE * 30 * DISCOUNT_RATE < 2000000
# ORDER BY DAILY_FEE DESC, CAR_TYPE, CAR_ID DESC

SELECT H.CAR_ID,
       P.CAR_TYPE,
       ROUND(DAILY_FEE * 30 * (100-DISCOUNT_RATE)/100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
) AND (P.CAR_TYPE = "세단" OR P.CAR_TYPE = "SUV") AND P.DURATION_TYPE = '30일 이상'
GROUP BY CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC

# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR AS C INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE = P.CAR_TYPE
# GROUP BY C.CAR_ID