-- 코드를 입력하세요
# SELECT DATE_FORMAT(SALES_DATE, '%Y') AS YEAR, DATE_FORMAT(SALES_DATE, '%m') AS MONTH, COUNT(*) AS PUCHASED_USERS, ROUND(COUNT(ONLINE_SALE_ID) / COUNT(A.USER_ID), 1) AS PUCHASED_RATIO
# FROM USER_INFO AS A INNER JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID
# WHERE DATE_FORMAT(SALES_DATE, '%Y') = 2021
# ORDER BY YEAR, MONTH

SELECT DATE_FORMAT(SALES_DATE, '%Y') AS YEAR,
       DATE_FORMAT(SALES_DATE, '%m') AS MONTH,
       COUNT(DISTINCT A.USER_ID) AS PUCHASED_USERS,
       ROUND(COUNT(DISTINCT A.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM USER_INFO AS A INNER JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID
WHERE DATE_FORMAT(JOINED, '%Y') = 2021
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH