-- 코드를 입력하세요
SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM ANIMAL_INS AS INS INNER JOIN ANIMAL_OUTS AS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE "%Intact%" AND (SEX_UPON_OUTCOME LIKE "%Spayed%" OR SEX_UPON_OUTCOME LIKE "%Neutered%")
ORDER BY INS.ANIMAL_ID