-- 코드를 입력하세요
# SELECT J.FLAVOR
# FROM FIRST_HALF AS F INNER JOIN JULY AS J ON F.FLAVOR = J.FLAVOR
# GROUP BY FLAVOR
# ORDER BY SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
# LIMIT 3


# SELECT *
# FROM FIRST_HALF AS F INNER JOIN JULY AS J ON F.FLAVOR = J.FLAVOR

# SELECT *
# FROM FIRST_HALF AS F INNER JOIN JULY AS J ON F.FLAVOR = J.FLAVOR

# SELECT * FROM FIRST_HALF
# UNION
# SELECT * FROM JULY
# GROUP BY SHIPMENT_ID
# HAVING SUM(TOTAL_ORDER)

# SELECT *
# FROM FIRST_HALF AS F INNER JOIN JULY AS J ON F. SHIPMENT_ID = J.SHIPMENT_ID

SELECT J.FLAVOR
FROM FIRST_HALF AS F INNER JOIN JULY AS J ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
LIMIT 3

# SELECT *
# FROM FIRST_HALF AS F INNER JOIN JULY AS J ON F.FLAVOR = J.FLAVOR

# SELECT *
# FROM FIRST_HALF F LEFT JOIN (
#     SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
#     FROM JULY
#     GROUP BY FLAVOR
# ) J ON F.FLAVOR = J.FLAVOR
# ORDER BY (F.TOTAL_ORDER + J.TOTAL_ORDER) DESC

# SELECT J.FLAVOR
# FROM FIRST_HALF F LEFT JOIN (
#     SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
#     FROM JULY
#     GROUP BY FLAVOR
# ) J ON F.FLAVOR = J.FLAVOR
# ORDER BY (F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
# LIMIT 3