-- 코드를 입력하세요
# SELECT *
# FROM FIRST_HALF AS F RIGHT OUTER JOIN JULY AS J ON F. SHIPMENT_ID = J.SHIPMENT_ID
# GROUP BY J.FLAVOR
# HAVING SUM(J.TOTAL_ORDER)
# ORDER BY SUM(J.TOTAL_ORDER)
# LIMIT 3

# SELECT * FROM FIRST_HALF
# UNION
# SELECT * FROM JULY
# GROUP BY SHIPMENT_ID
# HAVING SUM(TOTAL_ORDER)

# SELECT *
# FROM FIRST_HALF AS F INNER JOIN JULY AS J ON F. SHIPMENT_ID = J.SHIPMENT_ID

SELECT J.FLAVOR
FROM FIRST_HALF AS F INNER JOIN JULY AS J ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
LIMIT 3