-- 코드를 입력하세요
# SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
# FROM REST_REVIEW AS R INNER JOIN MEMBER_PROFILE AS M ON R.MEMBER_ID = M.MEMBER_ID
# # WHERE MAX(COUNT(MEMBER_NAME))
# ORDER BY REVIEW_DATE, REVIEW_TEXT

# SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
# FROM REST_REVIEW AS R INNER JOIN MEMBER_PROFILE AS M ON R.MEMBER_ID = M.MEMBER_ID
# GROUP BY R.MEMBER_ID
# HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM REST_REVIEW GROUP BY MEMBER_ID)
# ORDER BY REVIEW_DATE, REVIEW_TEXT

# SELECT COUNT(*)
# FROM REST_REVIEW
# # WHERE MAX(COUNT(MEMBER_NAME))
# ORDER BY REVIEW_DATE, REVIEW_TEXT



SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS R INNER JOIN MEMBER_PROFILE AS M ON R.MEMBER_ID = M.MEMBER_ID
WHERE M.MEMBER_ID = 
(SELECT MEMBER_ID FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(*) DESC LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT