-- 코드를 입력하세요
# SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
# FROM BOOK AS A INNER JOIN BOOK_SALES AS B ON A.BOOK_ID = B.BOOK_ID
# GROUP BY CATEGORY
# HAVING DATE_FORMAT(PUBLISHED_DATE, "%Y-%m") = "2022-01"
# ORDER BY CATEGORY

# SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
# FROM BOOK AS A INNER JOIN BOOK_SALES AS B ON A.BOOK_ID = B.BOOK_ID
# WHERE DATE_FORMAT(PUBLISHED_DATE, "%Y-%m") = "2022-01"
# GROUP BY CATEGORY
# ORDER BY CATEGORY

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS A INNER JOIN BOOK_SALES AS B ON A.BOOK_ID = B.BOOK_ID
WHERE SALES_DATE LIKE "%2022-01%"
GROUP BY CATEGORY
ORDER BY CATEGORY