-- 코드를 입력하세요
#SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SALES * PRICE AS TOTAL_SALES
#FROM BOOK AS B INNER JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID INNER JOIN (SELECT *                                                            FROM BOOK_SALES
#                WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01') AS S ON B.BOOK_ID = S.BOOK_ID
#GROUP BY AUTHOR_ID, CATEGORY
#ORDER BY AUTHOR_ID, CATEGORY DESC

#SELECT *
#FROM BOOK AS B INNER JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID INNER JOIN (SELECT *                                                            FROM BOOK_SALES
#                WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01') AS S ON B.BOOK_ID = S.BOOK_ID
# GROUP BY B.AUTHOR_ID, CATEGORY
# ORDER BY B.AUTHOR_ID, CATEGORY DESC

SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK AS B INNER JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID INNER JOIN (SELECT *                                                            FROM BOOK_SALES
                WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01') AS S ON B.BOOK_ID = S.BOOK_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC