-- 코드를 입력하세요
# SELECT HISTORY_ID, 
#     CASE
#         WHEN DATEDIFF(END_DATE, START_DATE)+1 < 7 THEN ROUND((DATEDIFF(END_DATE, START_DATE)+1) * DAILY_FEE)
#         WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 AND DATEDIFF(END_DATE, START_DATE)+1 <= 29 THEN ROUND(DAILY_FEE*(DATEDIFF(END_DATE, START_DATE)+1)*0.95)
#         WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 AND DATEDIFF(END_DATE, START_DATE)+1 <= 89 THEN ROUND(DAILY_FEE*(DATEDIFF(END_DATE, START_DATE)+1)*0.92)
#         WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN ROUND(DAILY_FEE*(DATEDIFF(END_DATE, START_DATE)+1)*0.85)
#     END AS FEE
# FROM CAR_RENTAL_COMPANY_CAR AS CAR INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY ON CAR.CAR_ID = HISTORY.CAR_ID INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN ON CAR.CAR_TYPE = PLAN.CAR_TYPE
# WHERE PLAN.CAR_TYPE = "트럭"
# GROUP BY HISTORY_ID
# ORDER BY DAILY_FEE DESC, HISTORY_ID DESC

SELECT B.HISTORY_ID, ROUND((DATEDIFF(B.END_DATE, B.START_DATE)+1) * A.DAILY_FEE * (
    CASE
        WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 < 7 THEN 1
        WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 < 30 THEN 0.95
        WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 < 90 THEN 0.92
        ELSE 0.85
    END
)) as FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC


# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR AS CAR INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY ON CAR.CAR_ID = HISTORY.CAR_ID INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN ON CAR.CAR_TYPE = PLAN.CAR_TYPE
# # WHERE PLAN.CAR_TYPE = "트럭"
# # GROUP BY HISTORY_ID
# ORDER BY DAILY_FEE DESC, HISTORY_ID DESC