-- 코드를 입력하세요
SELECT A.PRODUCT_ID, PRODUCT_NAME, PRICE*SUM(AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS A INNER JOIN FOOD_ORDER AS B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE, "%Y-%m") = "2022-05"
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID

# SELECT *
# FROM FOOD_PRODUCT AS A INNER JOIN FOOD_ORDER AS B ON A.PRODUCT_ID = B.PRODUCT_ID