-- 코드를 작성해주세요
select A.ITEM_ID, ITEM_NAME, RARITY
from ITEM_INFO as a INNER JOIN ITEM_TREE AS B ON A.ITEM_ID = B.ITEM_ID

where PARENT_ITEM_ID IN
(SELECT ITEM_ID
FROM ITEM_INFO
WHERE RARITY = 'RARE')
# PARENT_ITEM_ID = 0, 1 인 것만 남게됨
ORDER BY A.ITEM_ID DESC