-- 코드를 입력하세요
SELECT DISTINCT(CAR.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS CAR INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY ON CAR.CAR_ID = HISTORY.CAR_ID
WHERE CAR_TYPE = '세단' AND DATE_FORMAT(START_DATE, '%m') = 10
ORDER BY CAR.CAR_ID DESC