-- 코드를 입력하세요
# SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
# FROM USED_GOODS_BOARD AS B INNER JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
# WHERE STATUS = "DONE"
# GROUP BY USER_ID
# HAVING TOTAL_SALES >=700000
# ORDER BY TOTAL_SALES

SELECT USER_ID, NICKNAME, TOTAL AS TOTAL_SALES
FROM USED_GOODS_USER AS U INNER JOIN
    (SELECT WRITER_ID, SUM(PRICE) AS TOTAL
      FROM USED_GOODS_BOARD
      WHERE STATUS = "DONE"
      GROUP BY WRITER_ID
      HAVING SUM(PRICE) >= 700000) AS B ON U.USER_ID = B.WRITER_ID
ORDER BY TOTAL_SALES